# Generated by Django 5.1.6 on 2025-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_recipe_ingredients_recipe_instructions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="text",
        ),
        migrations.AddField(
            model_name="review",
            name="comment",
            field=models.TextField(default=""),
        ),
    ]
